// eslint-disable-next-line no-unused-vars
module.exports = [
  {
    reviewDate: 'Apr 15 2019',
    reviewId: 90260795,
    reviewMovieId: 9499977,
    reviewMovieName: 'Lord of the Rings',
    reviewRating: 5,
    reviewText: 'Dolores pariatur maxime atque minima ut libero dolorem asperiores. Iusto enim est. Sapienteased minus et. Est non ut deleniti possimus aspernatur. Rerum non magnam nam. Aut qui aut perferendis atasint sunt.',
    reviewerName: 'Mr. Jovan Dooley',
  },
  {
    reviewDate: 'Jul 27 2019',
    reviewId: 90260796,
    reviewMovieId: 9499977,
    reviewMovieName: 'Lord of the Rings',
    reviewRating: 1,
    reviewText: 'Id quia eveniet inventore deserunt delectus. Consectetur nihil saepe. Incidunt repellendusquia est at qui. Tempore nihil consequatur inventore nemo voluptatem et rerum. Non et quidem voluptatumvoluptatem molestiae vero',
    reviewerName: 'Keara Wunsch',
  },
  {
    reviewDate: 'Mar 03 2019',
    reviewId: 90260797,
    reviewMovieId: 9499977,
    reviewMovieName: 'Lord of the Rings',
    reviewRating: 3,
    reviewText: 'Dolorem incidunt voluptates accusamus consequatur voluptatum blanditiis ut ea. Minus abporro illo excepturi commodi natus. Asperiores hic a.',
    reviewerName: 'Sidney Bins',
  },
  {
    reviewDate: 'Apr 10 2019',
    reviewId: 90260798,
    reviewMovieId: 9499977,
    reviewMovieName: 'Lord of the Rings',
    reviewRating: 2,
    reviewText: 'Ut qui blanditiis officia sapiente voluptas. Eos blanditiis nihil temporibus ex facere nonaut. In facere eligendi quo. Placeat iste qui sint sit nam quod corporis quia. Eum qui debitis odio aliasmolestias nihil possimu',
    reviewerName: 'Mrs. Chanel Rippin',
  },
  {
    reviewDate: 'Aug 02 2019',
    reviewId: 90260799,
    reviewMovieId: 9499977,
    reviewMovieName: 'Lord of the Rings',
    reviewRating: 5,
    reviewText: 'Est voluptatem reiciendis et iste laboriosam autem sunt quos impedit. Quia sequi corruptiblanditiis. Rem provident sed ratione nemo deserunt eum fugit.',
    reviewerName: 'Julio Lynch Sr.',
  },
  {
    reviewDate: 'Jun 26 2019',
    reviewId: 90260800,
    reviewMovieId: 9499977,
    reviewMovieName: 'Lord of the Rings',
    reviewRating: 5,
    reviewText: 'Ut illo id autem rerum. Voluptatem maxime aliquam ut doloribus sint voluptas quilaboriosam. Accusantium veniam corporis quia commodi. Perspiciatis eum architecto blanditiis fugiatvoluptas et qui quasi distinctio.',
    reviewerName: 'Deontae Zieme',
  },
  {
    reviewDate: 'Jul 19 2019',
    reviewId: 90260801,
    reviewMovieId: 9499977,
    reviewMovieName: 'Lord of the Rings',
    reviewRating: 2,
    reviewText: 'Beatae odit sed quasi animi. Sunt ut quia porro corrupti ut tempora vitae accusamus. Quodqui corrupti ex aliquam est enim molestiae.',
    reviewerName: 'Giuseppe Hilll',
  },
];
